[build-system]

requires = [
    "setuptools>=42",
    "pandas>=1.2.4",
    "numpy>=1.20.3",
    "tqdm>=4.61.0",
    "beautifulsoup4>=4.9.1",
    "openpyxl>=3.0.9",
    "xlrd>=2.0.1",
]
build-backend = "setuptools.build_meta"